name: FTP

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy by rsync
        uses: Burnett01/rsync-deploy@v7.0.2
        with:
          switches: -avzr --delete
          path: ./cms/wp-content/themes/portfolio-s/
          remote_path: ${{ secrets.FTP_SERVER_DIR }}
          remote_host: ${{ secrets.SSH_HOSTNAME }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
