name: FTP

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 同期のための rsync コマンド。後ほど詳述
      - name: Deploy by rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude-from=.rsyncignore
          RSYNC_TARGET: cms/wp-content/themes/portfolio-s
          RSYNC_SOURCE: ./cms/wp-content/themes/portfolio-s
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
